
#include <iostream>
#include <vector>
#include <fstream>
#include <streampu.hpp>

#include <aff3ct.hpp>


// NOTE: Hardware block headers are added automatically by add_hardware_module.py
// Example: #include "VModel_increment.h"  // Generated by Verilator
#include "VerilatorSimulation.hpp"
#include "VModel_PassThrough.h"



#include "Comparator.hpp"

using namespace spu;
using namespace spu::module;

int main(int argc, char** argv)
{
    std::cout << "Starting Hulotte project..." << std::endl;


    // 1. Modules creation

    // RS(7, 5) => t=1, m=3. Bits 21 -> 15.
    // NOTE: This uses aff3ct B_32 (32-bit integer) template instantiation.
    const int N_rs = 7;  // Symbols
    const int K_rs = 5;  // Symbols
    const int m = 3;       // Bits per symbol
    const int t = (N_rs - K_rs) / 2; // Correction
    const int N = N_rs * m; // Total bits
    const int K = K_rs * m; // Info bits

    module::Source_random<> source(K);
    Comparator               comparator(K);

    // Create RS Polynomial Generator (needed for RS construction)
    aff3ct::tools::RS_polynomial_generator poly(N_rs, t);

    // Create Encoder and Decoder
    aff3ct::module::Encoder_RS<>     encoder(K_rs, N_rs, poly);
    aff3ct::module::Decoder_RS_std<> decoder(K_rs, N_rs, poly);

    

    
    
    // NOTE: Keep a single traced HW instance by default.
    VerilatorSimulation<VModel_PassThrough> hw_passthrough(K, "trace_main", true);
    

    // 2. Sockets binding
    using namespace aff3ct::module;
    using namespace aff3ct::tools;

    // in_ref: source directly to comparator (reference path)
    source[src::tsk::generate][(int)src::sck::generate::out_data] = comparator["check::in_ref"];

    // in_got: source -> [uart ->] [hw ->] [custom ->] encoder -> decoder -> comparator
    
    source[src::tsk::generate][(int)src::sck::generate::out_data] = hw_passthrough["simulate::input"];
    
    hw_passthrough["simulate::output"] = encoder[enc::tsk::encode][(int)enc::sck::encode::U_K];
    
    

    encoder[enc::tsk::encode][(int)enc::sck::encode::X_N]           = decoder[dec::tsk::decode_hiho][(int)dec::sck::decode_hiho::Y_N];
    decoder[dec::tsk::decode_hiho][(int)dec::sck::decode_hiho::V_K] = comparator["check::in_got"];



    // 3. Sequence creation
    std::vector<runtime::Task*> first_tasks;
    first_tasks.push_back(&source("generate"));

    runtime::Sequence sequence(first_tasks);

    // Configuration
    for (auto& type : sequence.get_tasks_per_types())
        for (auto& t : type)
        {
            t->set_stats(true);
            t->set_debug(true);
        }

    // 4. Execution
    std::cout << "Processing..." << std::endl;

    // Export dot file for visualization
    std::ofstream file("graph.dot");
    sequence.export_dot(file);

    // Run the sequence
    for (auto i = 0; i < 3; i++)
        sequence.exec_seq(); // Run 1 frame at a time

    // 5. Stats
    std::cout << "\nEnd of execution." << std::endl;
    tools::Stats::show(sequence.get_tasks_per_types(), true, false);

    // 6. Non-regression check
    if (comparator.has_errors())
        std::cerr << "[FAIL] " << comparator.get_n_errors() << " error(s) detected over "
                  << comparator.get_frame_count() << " frame(s)." << std::endl;
    else
        std::cout << "[PASS] 0 errors over " << comparator.get_frame_count() << " frame(s)." << std::endl;

    return comparator.has_errors() ? 1 : 0;
}
