"""Deterministic C++ generation for the first pipeline slice."""

from pathlib import Path

from .catalog import CatalogError, CatalogModule, ModuleCatalog
from .pipeline import ModuleSpec, Pipeline, PipelineCycleError


class GenerationError(ValueError):
    """Raised when a pipeline cannot be converted to C++."""


def _catalog_id(module: ModuleSpec) -> str:
    return module.catalog or module.module_id


def _constructor_arguments(module: ModuleSpec, catalog_module: CatalogModule, pipeline: Pipeline) -> list[str]:
    arguments: list[str] = []
    for argument in catalog_module.constructor:
        parameter = argument.get("parameter")
        resource = argument.get("resource")
        if parameter is not None and resource is not None:
            raise GenerationError(
                f"module '{module.module_id}' has an unsupported constructor argument"
            )
        if isinstance(resource, str):
            resource_spec = pipeline.resources.get(resource)
            if resource_spec is None:
                raise GenerationError(
                    f"module '{module.module_id}' references unknown resource '{resource}'"
                )
            arguments.append(resource)
            continue
        if not isinstance(parameter, str):
            raise GenerationError(
                f"module '{module.module_id}' has an unsupported constructor argument"
            )
        if parameter not in module.parameters:
            raise GenerationError(
                f"module '{module.module_id}' is missing constructor parameter '{parameter}'"
            )
        value = module.parameters[parameter]
        if isinstance(value, bool) or not isinstance(value, (int, float, str)):
            raise GenerationError(
                f"module '{module.module_id}' parameter '{parameter}' must be a scalar"
            )
        arguments.append(str(value).lower() if isinstance(value, bool) else str(value))
    return arguments


def _resolve_modules(pipeline: Pipeline, catalog: ModuleCatalog):
    resolved = []
    includes: set[str] = set()
    try:
        module_order = pipeline.topological_order()
    except PipelineCycleError as error:
        raise GenerationError(str(error)) from error
    for module_id in module_order:
        module = pipeline.modules[module_id]
        try:
            catalog_module = catalog.resolve(_catalog_id(module))
        except CatalogError as error:
            raise GenerationError(str(error)) from error
        if catalog_module.kind != module.kind:
            raise GenerationError(
                f"module '{module_id}' type '{module.kind}' does not match catalog type "
                f"'{catalog_module.kind}'"
            )
        if module.class_name and module.class_name != catalog_module.class_name:
            raise GenerationError(
                f"module '{module_id}' class does not match catalog entry '{catalog_module.catalog_id}'"
            )
        includes.add(catalog_module.include)
        resolved.append((module, catalog_module))
    for resource in pipeline.resources.values():
        try:
            includes.add(catalog.resolve_resource(resource.kind).include)
        except CatalogError as error:
            raise GenerationError(str(error)) from error
    return resolved, sorted(includes)


def generate_cpp(pipeline: Pipeline, catalog: ModuleCatalog) -> str:
    """Generate a deterministic standalone C++ pipeline source."""
    resolved, includes = _resolve_modules(pipeline, catalog)
    lines = ["// Generated by Hulotte. Do not edit.", "#include <streampu.hpp>"]
    lines.extend(f'#include "{include}"' for include in includes if include != "streampu.hpp")
    lines.extend(
        [
            "",
            "#include <vector>",
            "",
            "using namespace spu;",
            "using namespace spu::module;",
        ]
    )
    if any(module.kind == "aff3ct" for module in pipeline.modules.values()):
        lines.extend(
            [
                "using namespace aff3ct::module;",
                "using namespace aff3ct::tools;",
            ]
        )
    lines.extend(["", "int main()", "{"])

    source_ids = set(pipeline.source_modules())
    for resource_id in sorted(pipeline.resources):
        resource = pipeline.resources[resource_id]
        try:
            catalog_resource = catalog.resolve_resource(resource.kind)
        except CatalogError as error:
            raise GenerationError(str(error)) from error
        arguments = ", ".join(
            _resource_constructor_arguments(resource_id, resource.parameters, catalog_resource.constructor)
        )
        lines.append(f"    {catalog_resource.class_name} {resource_id}({arguments});")

    for module, catalog_module in resolved:
        arguments = ", ".join(_constructor_arguments(module, catalog_module, pipeline))
        lines.append(f"    {catalog_module.class_name} {module.module_id}({arguments});")

    lines.extend(["", "    std::vector<runtime::Task*> first_tasks;"])
    for module, catalog_module in resolved:
        if module.module_id in source_ids:
            first_task = _first_task(catalog_module.sockets)
        else:
            first_task = None
        if first_task:
            lines.append(f'    first_tasks.push_back(&{module.module_id}("{first_task}"));')
    lines.extend(
        [
            "    runtime::Sequence sequence(first_tasks);",
            "",
        ]
    )
    resolved_by_id = {module.module_id: catalog_module for module, catalog_module in resolved}
    for connection in pipeline.connections:
        source = _binding_endpoint(connection.source, "source", resolved_by_id)
        target = _binding_endpoint(connection.target, "target", resolved_by_id)
        lines.append(
            f"    {source} = {target};"
        )
    lines.extend(
        [
            "",
            "    sequence.exec_seq();",
            "    return 0;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def write_cpp(output_path: str | Path, pipeline: Pipeline, catalog: ModuleCatalog) -> Path:
    """Generate C++ and write it only after successful resolution."""
    content = generate_cpp(pipeline, catalog)
    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")
    return destination


def _parse_endpoint(endpoint: str, label: str) -> tuple[str, str, str]:
    parts = endpoint.split(".") if isinstance(endpoint, str) else []
    if len(parts) != 3 or not all(parts):
        raise GenerationError(f"invalid {label} endpoint '{endpoint}'")
    return parts[0], parts[1], parts[2]


def _resource_constructor_arguments(
    resource_id: str, parameters: dict, constructor: tuple[dict, ...]
) -> list[str]:
    arguments: list[str] = []
    for argument in constructor:
        parameter = argument.get("parameter")
        if not isinstance(parameter, str) or parameter not in parameters:
            raise GenerationError(
                f"resource '{resource_id}' is missing constructor parameter '{parameter}'"
            )
        value = parameters[parameter]
        if isinstance(value, bool) or not isinstance(value, (int, float, str)):
            raise GenerationError(
                f"resource '{resource_id}' parameter '{parameter}' must be a scalar"
            )
        arguments.append(str(value).lower() if isinstance(value, bool) else str(value))
    return arguments


def _binding_endpoint(endpoint: str, label: str, resolved: dict[str, CatalogModule]) -> str:
    module_id, task, socket = _parse_endpoint(endpoint, label)
    module = resolved.get(module_id)
    if module is None:
        raise GenerationError(f"{label} endpoint '{endpoint}' references an unknown module")
    socket_spec = module.sockets.get(task, {}).get(
        "outputs" if label == "source" else "inputs", {}
    ).get(socket, {})
    cpp_task = socket_spec.get("cpp_task")
    cpp_socket = socket_spec.get("cpp_socket")
    if cpp_task and cpp_socket:
        return f'{module_id}[{cpp_task}][{cpp_socket}]'
    return f'{module_id}["{task}::{socket}"]'


def _first_task(sockets: dict) -> str | None:
    if not isinstance(sockets, dict):
        return None
    for task in sorted(sockets):
        return task
    return None
