
#include <iostream>
#include <vector>
#include <memory>
#include <fstream>
#include <streampu.hpp>


// NOTE: Hardware block headers are added automatically by add_hardware_module.py
// Example: #include "VModel_increment.h"  // Generated by Verilator
#include "VerilatorSimulation.hpp"
#include "VModel_PassThrough.h"
#include "VModel_PassThrough_add.h"



using namespace spu;
using namespace spu::module;

int main(int argc, char** argv)
{
    std::cout << "Starting Hulotte project..." << std::endl;


    // 1. Modules creation
    
    const int n_elmts = 16;
    module::Source_random<int> source(n_elmts);
    module::Finalizer  <int> finalizer(n_elmts);
    
    
    // NOTE: Only ONE Verilator instance can have tracing enabled due to Verilator context limitations
    auto hw_passthrough = std::make_unique<VerilatorSimulation<VModel_PassThrough>>(n_elmts, "trace_main", true);
    auto hw_passthrough2 = std::make_unique<VerilatorSimulation<VModel_PassThrough>>(n_elmts, "trace_main2", true);
    auto hw_passthrough_add = std::make_unique<VerilatorSimulation<VModel_PassThrough_add>>(n_elmts, "trace_add", true);
    // Additional hardware blocks can be added using add_hardware_module.py
    // They are created with trace DISABLED to avoid Verilator context conflicts
    // Example (add via script):
    //   #include "VModel_increment.h"
    //   auto hw_increment = std::make_unique<VerilatorSimulation<VModel_increment>>(n_elmts, "trace_increment", false);
    
    
    // 2. Sockets binding
    
    // Default chain: Source -> PassThrough -> (Custom Module) -> Finalizer
    source  ["generate::out_data"] = (*hw_passthrough) ["simulate::input"];
    
    (*hw_passthrough) ["simulate::output"] = (*hw_passthrough_add) ["simulate::input"];
    
    (*hw_passthrough_add) ["simulate::output"] =finalizer ["finalize::in"];
    
    
    // Additional hardware blocks can be connected here
    // Example: source["generate::out_data"] = (*hw_passthrough) ["simulate::input"];
    //          (*hw_passthrough) ["simulate::output"] = (*hw_increment) ["simulate::input"];
    //          (*hw_increment) ["simulate::output"] = finalizer["finalize::in"];
    


    // 3. Sequence creation
    std::vector<runtime::Task*> first_tasks;

    first_tasks.push_back(&source("generate"));


    runtime::Sequence sequence(first_tasks);

    // Configuration
    for (auto& type : sequence.get_tasks_per_types())
        for (auto& t : type)
        {
            t->set_stats(true);
            t->set_debug(true);
        }

    // 4. Execution
    std::cout << "Processing..." << std::endl;
    
    // Export dot file for visualization
    std::ofstream file("graph.dot");
    sequence.export_dot(file);

    // Run the sequence
    for (auto i = 0; i < 3; i++)
        sequence.exec_seq(); // Run 1 frame at a time

    // 5. Stats
    std::cout << "\\nEnd of execution." << std::endl;
    tools::Stats::show(sequence.get_tasks_per_types(), true, false);

    return 0;
}
